import { CreateRoutineDto } from '../../routine/dto/create-routine.dto';

export const ADVANCED_ROUTINE: CreateRoutineDto = {
  title: '상급자용 고급 분할 루틴',
  description: '상급자를 위한 고강도 근비대 분할 루틴',
  goalType: 'MUSCLE_GAIN',
  experienceLevel: 'ADVANCED',
  weeklyFrequency: 5,
  days: [
    {
      dayIndex: 0,
      name: '가슴',
      bodyPart: 'CHEST',
      subExercises: [
        {
          order: 0,
          sets: 5,
          reps: 5,
          oneRmPct: 0.85,
          exerciseName: '벤치프레스',
          bodyPart: 'CHEST',
        },
        {
          order: 1,
          sets: 4,
          reps: 8,
          oneRmPct: 0.75,
          exerciseName: '인클라인 벤치프레스',
          bodyPart: 'CHEST',
        },
        {
          order: 2,
          sets: 3,
          reps: 10,
          oneRmPct: 0.65,
          exerciseName: '딥스',
          bodyPart: 'CHEST',
        },
        {
          order: 3,
          sets: 3,
          reps: 12,
          bodyPart: 'CHEST',
          chooseOneExercises: '케이블크로스오버, 딥스, 펙덱 플라이 택 1개',
        },
      ],
    },
    {
      dayIndex: 1,
      name: '등',
      bodyPart: 'BACK',
      subExercises: [
        {
          order: 0,
          sets: 5,
          reps: 5,
          oneRmPct: 0.65,
          exerciseName: '데드리프트',
          bodyPart: 'BACK',
        },
        {
          order: 1,
          sets: 4,
          reps: 8,
          oneRmPct: 0.5,
          exerciseName: '펜들레이로우',
          bodyPart: 'BACK',
        },
        {
          order: 2,
          sets: 4,
          reps: 10,
          oneRmPct: 0.2,
          exerciseName: '바벨로우',
          bodyPart: 'BACK',
        },
        {
          order: 3,
          sets: 3,
          reps: 12,
          oneRmPct: 0.5,
          exerciseName: '풀업',
          bodyPart: 'BACK',
        },
        {
          order: 4,
          sets: 3,
          reps: 15,
          bodyPart: 'BACK',
          chooseOneExercises: '시티드 로우, 원암 덤벨로우 택 1개',
        },
      ],
    },
    {
      dayIndex: 2,
      name: '하체',
      bodyPart: 'LEGS',
      subExercises: [
        {
          order: 0,
          sets: 5,
          reps: 5,
          oneRmPct: 0.85,
          exerciseName: '스쿼트',
          bodyPart: 'LEGS',
        },
        {
          order: 1,
          sets: 4,
          reps: 8,
          oneRmPct: 0.75,
          exerciseName: '프론트 스쿼트',
          bodyPart: 'LEGS',
        },
        {
          order: 2,
          sets: 4,
          reps: 10,
          oneRmPct: 0.65,
          exerciseName: '루마니안 데드리프트',
          bodyPart: 'LEGS',
        },
        {
          order: 3,
          sets: 3,
          reps: 12,
          bodyPart: 'LEGS',
          chooseOneExercises: '레그프레스, 레그익스텐션 택 1개',
        },
        {
          order: 4,
          sets: 3,
          reps: 15,
          bodyPart: 'LEGS',
          chooseOneExercises: '레그컬, 카프레이즈 택 1개',
        },
      ],
    },
    {
      dayIndex: 3,
      name: '어깨',
      bodyPart: 'SHOULDERS',
      subExercises: [
        {
          order: 0,
          sets: 5,
          reps: 5,
          oneRmPct: 0.85,
          exerciseName: '오버헤드 프레스',
          bodyPart: 'SHOULDERS',
        },
        {
          order: 1,
          sets: 4,
          reps: 8,
          bodyPart: 'SHOULDERS',
          chooseOneExercises: '비하인드 넥 프레스, 아놀드 프레스 택 1개',
        },
        {
          order: 2,
          sets: 4,
          reps: 12,
          bodyPart: 'SHOULDERS',
          chooseOneExercises: '레터럴 레이즈, 프론트 레이즈 택 1개',
        },
        {
          order: 3,
          sets: 3,
          reps: 15,
          bodyPart: 'SHOULDERS',
          chooseOneExercises: '벤트오버 레터럴 레이즈, 리어 델트 플라이 택 1개',
        },
      ],
    },
    {
      dayIndex: 4,
      name: '팔',
      bodyPart: 'ARMS',
      subExercises: [
        {
          order: 0,
          sets: 4,
          reps: 8,
          oneRmPct: 0.6,
          exerciseName: '클로즈그립 벤치프레스',
          bodyPart: 'ARMS',
        },
        {
          order: 1,
          sets: 4,
          reps: 10,
          oneRmPct: 0.5,
          bodyPart: 'ARMS',
          chooseOneExercises: '라잉 트라이셉스 익스텐션, 케이블푸쉬다운 택 1개',
        },
        {
          order: 2,
          sets: 4,
          reps: 10,
          oneRmPct: 0.4,
          exerciseName: '바벨컬',
          bodyPart: 'ARMS',
        },
        {
          order: 3,
          sets: 3,
          reps: 12,
          bodyPart: 'ARMS',
          chooseOneExercises: '해머컬, 케이블컬 택 1개',
        },
      ],
    },
  ],
};
