import { CreateRoutineDto } from '../../routine/dto/create-routine.dto';

export const FAT_LOSS_ROUTINE: CreateRoutineDto = {
  title: '체지방 감소 집중 루틴',
  description: '체지방 감소와 대사 향상에 최적화된 루틴',
  goalType: 'FAT_LOSS',
  experienceLevel: 'INTERMEDIATE',
  weeklyFrequency: 5,
  days: [
    {
      dayIndex: 0,
      name: '전신 메트콘',
      bodyPart: 'FULL_BODY',
      subExercises: [
        {
          order: 0,
          sets: 3,
          reps: 15,
          oneRmPct: 0.6,
          exerciseName: '스쿼트',
          bodyPart: 'LEGS',
        },
        {
          order: 1,
          sets: 3,
          reps: 15,
          bodyPart: 'CHEST',
          chooseOneExercises: '푸시업, 덤벨 프레스 택 1개',
        },
        {
          order: 2,
          sets: 3,
          reps: 15,
          bodyPart: 'BACK',
          chooseOneExercises: '바디웨이트 로우, 덤벨로우 택 1개',
        },
        {
          order: 3,
          sets: 3,
          reps: 30,
          bodyPart: 'LEGS',
          chooseOneExercises: '버피, 마운틴 클라이머, 줄넘기 택 1개',
        },
      ],
    },
    {
      dayIndex: 1,
      name: '상체 대사 스트레스',
      bodyPart: 'CHEST',
      subExercises: [
        {
          order: 0,
          sets: 3,
          reps: 12,
          oneRmPct: 0.65,
          exerciseName: '벤치프레스',
          bodyPart: 'CHEST',
        },
        {
          order: 1,
          sets: 3,
          reps: 12,
          oneRmPct: 0.2,
          exerciseName: '바벨로우',
          bodyPart: 'BACK',
        },
        {
          order: 2,
          sets: 3,
          reps: 15,
          bodyPart: 'SHOULDERS',
          chooseOneExercises: '레터럴 레이즈, 프론트 레이즈 택 1개',
        },
        {
          order: 3,
          sets: 3,
          reps: 20,
          bodyPart: 'CORE',
          chooseOneExercises: '플랭크, 행잉 레그레이즈 택 1개',
        },
      ],
    },
    {
      dayIndex: 2,
      name: '하체 + 심박 상승',
      bodyPart: 'LEGS',
      subExercises: [
        {
          order: 0,
          sets: 3,
          reps: 15,
          oneRmPct: 0.6,
          exerciseName: '스쿼트',
          bodyPart: 'LEGS',
        },
        {
          order: 1,
          sets: 3,
          reps: 20,
          bodyPart: 'LEGS',
          chooseOneExercises: '레그프레스, 워킹 런지 택 1개',
        },
        {
          order: 2,
          sets: 3,
          reps: 20,
          bodyPart: 'LEGS',
          chooseOneExercises: '레그컬, 카프레이즈 택 1개',
        },
        {
          order: 3,
          sets: 3,
          reps: 30,
          bodyPart: 'LEGS',
          chooseOneExercises: '점프스쿼트, 버피 택 1개',
        },
      ],
    },
    {
      dayIndex: 3,
      name: '등 중심 전신',
      bodyPart: 'BACK',
      subExercises: [
        {
          order: 0,
          sets: 3,
          reps: 12,
          exerciseName: '풀업',
          bodyPart: 'BACK',
        },
        {
          order: 1,
          sets: 3,
          reps: 15,
          exerciseName: '랫풀다운',
          bodyPart: 'BACK',
        },
        {
          order: 2,
          sets: 3,
          reps: 15,
          bodyPart: 'SHOULDERS',
          chooseOneExercises: '페이스풀, 레터럴 레이즈 택 1개',
        },
        {
          order: 3,
          sets: 3,
          reps: 30,
          bodyPart: 'LEGS',
          chooseOneExercises: '마운틴 클라이머, 로잉머신 택 1개',
        },
      ],
    },
    {
      dayIndex: 4,
      name: '서킷 트레이닝',
      bodyPart: 'FULL_BODY',
      subExercises: [
        {
          order: 0,
          sets: 4,
          reps: 12,
          bodyPart: 'CHEST',
          chooseOneExercises: '푸시업, 덤벨 프레스 택 1개',
        },
        {
          order: 1,
          sets: 4,
          reps: 12,
          bodyPart: 'BACK',
          chooseOneExercises: '덤벨로우, 케이블로우 택 1개',
        },
        {
          order: 2,
          sets: 4,
          reps: 20,
          bodyPart: 'LEGS',
          chooseOneExercises: '버피, 점프스쿼트, 마운틴 클라이머 택 1개',
        },
      ],
    },
  ],
};
