import { CreateRoutineDto } from '../../routine/dto/create-routine.dto';

export const GIANT_ROUTINE = {
  title: '벌크업 루틴',
  description: '최대 근비대를 위한 고빈도 고용량 벌크업 루틴',
  goalType: 'MUSCLE_GAIN',
  experienceLevel: 'ADVANCED',
  weeklyFrequency: 6,
  days: [
    {
      dayIndex: 0,
      name: '가슴 / 등',
      subExercises: [
        {
          order: 0,
          sets: 2,
          reps: 6,
          oneRmPct: 0.55,
          exerciseName: '벤치프레스',
          bodyPart: 'CHEST',
        },
        {
          order: 1,
          sets: 3,
          reps: 12,
          oneRmPct: 0.45,
          exerciseName: '인클라인 벤치',
          bodyPart: 'CHEST',
        },
        {
          order: 2,
          sets: 3,
          reps: 10,
          bodyPart: 'CHEST',
          chooseOneExercises:
            '딥스, 덤벨프레스, 인클라인덤벨프레스, 케이블크로스오버 택 1개',
        },
        {
          order: 3,
          sets: 2,
          reps: 6,
          oneRmPct: 0.35,
          exerciseName: '펜들레이로우',
          bodyPart: 'BACK',
        },
        {
          order: 4,
          sets: 3,
          reps: 12,
          oneRmPct: 0.25,
          exerciseName: '바벨로우',
          bodyPart: 'BACK',
        },
        {
          order: 5,
          sets: 3,
          reps: 10,
          bodyPart: 'BACK',
          chooseOneExercises: '풀업,랫풀다운,시티드로우,암풀다운 택1',
        },
      ],
    },
    {
      dayIndex: 1,
      name: '하체전면 / 어깨',
      subExercises: [
        {
          order: 0,
          sets: 2,
          reps: 6,
          oneRmPct: 0.55,
          exerciseName: '스쿼트',
          bodyPart: 'LEGS',
          memo: '(5T2P)',
        },
        {
          order: 1,
          sets: 3,
          reps: 12,
          oneRmPct: 0.35,
          exerciseName: '프론트 스쿼트',
          bodyPart: 'LEGS',
        },
        {
          order: 2,
          sets: 3,
          reps: 10,
          bodyPart: 'LEGS',
          chooseOneExercises: '쉬림프스쿼트, 레그익스텐션 택 1개',
        },
        {
          order: 3,
          sets: 2,
          reps: 6,
          oneRmPct: 0.55,
          exerciseName: 'OHP',
          bodyPart: 'SHOULDERS',
          memo: '(5T2P)',
        },
        {
          order: 4,
          sets: 3,
          reps: 12,
          oneRmPct: 0.4,
          exerciseName: '비하인드 넥 프레스',
          bodyPart: 'SHOULDERS',
        },
        {
          order: 5,
          sets: 3,
          reps: 10,
          bodyPart: 'SHOULDERS',
          chooseOneExercises: '레터럴레이즈, 벤트오버레터럴레이즈 택 1개',
        },
      ],
    },
    {
      dayIndex: 2,
      name: '하체후면 / 팔',
      subExercises: [
        {
          order: 0,
          sets: 2,
          reps: 6,
          oneRmPct: 0.55,
          exerciseName: '데드리프트',
          bodyPart: 'LEGS',
        },
        {
          order: 1,
          sets: 3,
          reps: 12,
          oneRmPct: 0.45,
          exerciseName: '데드리프트',
          bodyPart: 'LEGS',
        },
        {
          order: 2,
          sets: 3,
          reps: 10,
          bodyPart: 'LEGS',
          chooseOneExercises: '스티프레그데드리프트, 레그컬 택 1개',
        },
        {
          order: 3,
          sets: 2,
          reps: 6,
          oneRmPct: 0.5,
          exerciseName: '클로즈벤치',
          bodyPart: 'ARMS',
          memo: '(5T2P)',
        },
        {
          order: 4,
          sets: 3,
          reps: 10,
          bodyPart: 'ARMS',
          memo: '삼두',
          chooseOneExercises: '라잉트라이셉스 익스텐션, 케이블푸쉬다운 택 1개',
        },
        {
          order: 5,
          sets: 3,
          reps: 10,
          bodyPart: 'ARMS',
          memo: '이두',
          chooseOneExercises: '바벨컬, 덤벨컬, 해머컬 택 1개',
        },
        {
          order: 6,
          sets: 3,
          reps: 10,
          bodyPart: 'ARMS',
          memo: '이두',
          chooseOneExercises: '바벨컬, 덤벨컬, 해머컬 택 1개',
        },
      ],
    },
    {
      dayIndex: 3,
      name: '가슴 / 등',
      subExercises: [
        {
          order: 0,
          sets: 2,
          reps: 6,
          oneRmPct: 0.6,
          exerciseName: '벤치프레스',
          bodyPart: 'CHEST',
        },
        {
          order: 1,
          sets: 3,
          reps: 12,
          oneRmPct: 0.5,
          exerciseName: '인클라인 벤치',
          bodyPart: 'CHEST',
        },
        {
          order: 2,
          sets: 3,
          reps: 10,
          bodyPart: 'CHEST',
          chooseOneExercises:
            '딥스, 덤벨프레스, 인클라인덤벨프레스, 케이블크로스오버 택 1개',
        },
        {
          order: 3,
          sets: 2,
          reps: 6,
          oneRmPct: 0.4,
          exerciseName: '펜들레이로우',
          bodyPart: 'BACK',
        },
        {
          order: 4,
          sets: 3,
          reps: 12,
          oneRmPct: 0.3,
          exerciseName: '바벨로우',
          bodyPart: 'BACK',
        },
        {
          order: 5,
          sets: 3,
          reps: 10,
          bodyPart: 'BACK',
          chooseOneExercises: '풀업,랫풀다운,시티드로우,암풀다운 택1',
        },
      ],
    },
    {
      dayIndex: 4,
      name: '하체전면 / 어깨',
      subExercises: [
        {
          order: 0,
          sets: 2,
          reps: 6,
          oneRmPct: 0.6,
          exerciseName: '스쿼트',
          bodyPart: 'LEGS',
          memo: '(5T2P)',
        },
        {
          order: 1,
          sets: 3,
          reps: 12,
          oneRmPct: 0.4,
          exerciseName: '프론트 스쿼트',
          bodyPart: 'LEGS',
        },
        {
          order: 2,
          sets: 3,
          reps: 10,
          bodyPart: 'LEGS',
          chooseOneExercises: '쉬림프스쿼트, 레그익스텐션 택 1개',
        },
        {
          order: 3,
          sets: 2,
          reps: 6,
          oneRmPct: 0.6,
          exerciseName: 'OHP',
          bodyPart: 'SHOULDERS',
          memo: '(5T2P)',
        },
        {
          order: 4,
          sets: 3,
          reps: 12,
          oneRmPct: 0.5,
          exerciseName: '비하인드 넥 프레스',
          bodyPart: 'SHOULDERS',
        },
        {
          order: 5,
          sets: 3,
          reps: 10,
          bodyPart: 'SHOULDERS',
          chooseOneExercises: '레터럴레이즈, 벤트오버레터럴레이즈 택 1개',
        },
      ],
    },
    {
      dayIndex: 5,
      name: '하체후면 / 팔',
      subExercises: [
        {
          order: 0,
          sets: 2,
          reps: 6,
          oneRmPct: 0.6,
          exerciseName: '데드리프트',
          bodyPart: 'LEGS',
        },
        {
          order: 1,
          sets: 3,
          reps: 12,
          oneRmPct: 0.5,
          exerciseName: '데드리프트',
          bodyPart: 'LEGS',
        },
        {
          order: 2,
          sets: 3,
          reps: 10,
          bodyPart: 'LEGS',
          chooseOneExercises: '스티프레그데드리프트, 레그컬 택 1개',
        },
        {
          order: 3,
          sets: 2,
          reps: 6,
          oneRmPct: 0.6,
          exerciseName: '클로즈벤치',
          bodyPart: 'ARMS',
          memo: '(5T2P)',
        },
        {
          order: 4,
          sets: 3,
          reps: 10,
          bodyPart: 'ARMS',
          memo: '삼두',
          chooseOneExercises: '라잉트라이셉스 익스텐션, 케이블푸쉬다운 택 1개',
        },
        {
          order: 5,
          sets: 3,
          reps: 10,
          bodyPart: 'ARMS',
          memo: '이두',
          chooseOneExercises: '바벨컬, 덤벨컬, 해머컬 택 1개',
        },
        {
          order: 6,
          sets: 3,
          reps: 10,
          bodyPart: 'ARMS',
          memo: '이두',
          chooseOneExercises: '바벨컬, 덤벨컬, 해머컬 택 1개',
        },
      ],
    },
  ],
} as CreateRoutineDto;
