import { CreateRoutineDto } from '../../routine/dto/create-routine.dto';

export const INTERMEDIATE_ROUTINE: CreateRoutineDto = {
  title: '중급자용 분할 루틴',
  description: '중급자를 위한 근비대 중심 분할 루틴',
  goalType: 'MUSCLE_GAIN',
  experienceLevel: 'INTERMEDIATE',
  weeklyFrequency: 4,
  days: [
    {
      dayIndex: 0,
      name: '가슴 / 삼두',
      bodyPart: 'CHEST',
      subExercises: [
        {
          order: 0,
          sets: 4,
          reps: 8,
          oneRmPct: 0.75,
          exerciseName: '벤치프레스',
          bodyPart: 'CHEST',
        },
        {
          order: 1,
          sets: 3,
          reps: 10,
          exerciseName: '인클라인 덤벨 프레스',
          bodyPart: 'CHEST',
        },
        {
          order: 2,
          sets: 3,
          reps: 12,
          bodyPart: 'CHEST',
          chooseOneExercises: '딥스, 케이블크로스오버 택 1개',
        },
        {
          order: 3,
          sets: 3,
          reps: 10,
          bodyPart: 'ARMS',
          chooseOneExercises: '트라이셉스 익스텐션, 케이블푸쉬다운 택 1개',
        },
      ],
    },
    {
      dayIndex: 1,
      name: '등 / 이두',
      bodyPart: 'BACK',
      subExercises: [
        {
          order: 0,
          sets: 4,
          reps: 8,
          oneRmPct: 0.7,
          exerciseName: '데드리프트',
          bodyPart: 'BACK',
        },
        {
          order: 1,
          sets: 3,
          reps: 10,
          oneRmPct: 0.2,
          exerciseName: '바벨로우',
          bodyPart: 'BACK',
        },
        {
          order: 2,
          sets: 3,
          reps: 12,
          exerciseName: '랫풀다운',
          bodyPart: 'BACK',
        },
        {
          order: 3,
          sets: 3,
          reps: 10,
          bodyPart: 'ARMS',
          chooseOneExercises: '바벨컬, 해머컬 택 1개',
        },
      ],
    },
    {
      dayIndex: 2,
      name: '하체',
      bodyPart: 'LEGS',
      subExercises: [
        {
          order: 0,
          sets: 4,
          reps: 8,
          oneRmPct: 0.75,
          exerciseName: '스쿼트',
          bodyPart: 'LEGS',
        },
        {
          order: 1,
          sets: 3,
          reps: 10,
          exerciseName: '루마니안 데드리프트',
          bodyPart: 'LEGS',
        },
        {
          order: 2,
          sets: 3,
          reps: 12,
          bodyPart: 'LEGS',
          chooseOneExercises: '레그프레스, 레그익스텐션 택 1개',
        },
        {
          order: 3,
          sets: 3,
          reps: 15,
          bodyPart: 'LEGS',
          chooseOneExercises: '레그컬, 카프레이즈 택 1개',
        },
      ],
    },
    {
      dayIndex: 3,
      name: '어깨 / 복근',
      bodyPart: 'SHOULDERS',
      subExercises: [
        {
          order: 0,
          sets: 4,
          reps: 8,
          oneRmPct: 0.7,
          exerciseName: '오버헤드 프레스',
          bodyPart: 'SHOULDERS',
        },
        {
          order: 1,
          sets: 3,
          reps: 12,
          bodyPart: 'SHOULDERS',
          chooseOneExercises: '레터럴 레이즈, 프론트 레이즈 택 1개',
        },
        {
          order: 2,
          sets: 3,
          reps: 12,
          bodyPart: 'SHOULDERS',
          chooseOneExercises: '벤트오버 레터럴 레이즈, 리어 델트 플라이 택 1개',
        },
        {
          order: 3,
          sets: 3,
          reps: 15,
          bodyPart: 'CHEST',
          chooseOneExercises: '크런치, 플랭크 택 1개',
        },
      ],
    },
  ],
};
