import { CreateRoutineDto } from '../../routine/dto/create-routine.dto';

export const STRENGTH_ROUTINE: CreateRoutineDto = {
  title: '근력증가용 루틴',
  description: '근력 향상에 특화된 저반복 고중량 루틴',
  goalType: 'MUSCLE_GAIN',
  experienceLevel: 'INTERMEDIATE',
  weeklyFrequency: 4,
  days: [
    {
      dayIndex: 0,
      name: '상체 근력',
      bodyPart: 'CHEST',
      subExercises: [
        {
          order: 0,
          sets: 5,
          reps: 5,
          oneRmPct: 0.7,
          exerciseName: '벤치프레스',
          bodyPart: 'CHEST',
        },
        {
          order: 1,
          sets: 4,
          reps: 6,
          oneRmPct: 0.7,
          exerciseName: '인클라인 벤치프레스',
          bodyPart: 'CHEST',
        },
        {
          order: 2,
          sets: 3,
          reps: 5,
          oneRmPct: 0.6,
          exerciseName: '펜들레이로우',
          bodyPart: 'BACK',
        },
        {
          order: 3,
          sets: 3,
          reps: 8,
          oneRmPct: 0.5,
          exerciseName: '바벨로우',
          bodyPart: 'BACK',
        },
      ],
    },
    {
      dayIndex: 1,
      name: '하체 근력',
      bodyPart: 'LEGS',
      subExercises: [
        {
          order: 0,
          sets: 5,
          reps: 5,
          oneRmPct: 0.7,
          exerciseName: '스쿼트',
          bodyPart: 'LEGS',
        },
        {
          order: 1,
          sets: 4,
          reps: 6,
          oneRmPct: 0.6,
          exerciseName: '프론트 스쿼트',
          bodyPart: 'LEGS',
        },
        {
          order: 2,
          sets: 3,
          reps: 5,
          oneRmPct: 0.5,
          exerciseName: '루마니안 데드리프트',
          bodyPart: 'LEGS',
        },
        {
          order: 3,
          sets: 3,
          reps: 8,
          bodyPart: 'LEGS',
          oneRmPct: 0.4,
          chooseOneExercises: '레그프레스, 레그익스텐션 택 1개',
        },
      ],
    },
    {
      dayIndex: 2,
      name: '상체 근력',
      bodyPart: 'BACK',
      subExercises: [
        {
          order: 0,
          sets: 5,
          reps: 5,
          oneRmPct: 0.7,
          exerciseName: '데드리프트',
          bodyPart: 'BACK',
        },
        {
          order: 1,
          sets: 4,
          reps: 6,
          oneRmPct: 0.6,
          exerciseName: '오버헤드 프레스',
          bodyPart: 'SHOULDERS',
        },
        {
          order: 2,
          sets: 3,
          reps: 5,
          oneRmPct: 0.5,
          exerciseName: '인클라인 벤치프레스',
          bodyPart: 'CHEST',
        },
        {
          order: 3,
          sets: 3,
          reps: 8,
          oneRmPct: 0.4,
          exerciseName: '풀업',
          bodyPart: 'BACK',
        },
      ],
    },
    {
      dayIndex: 3,
      name: '하체 근력',
      bodyPart: 'LEGS',
      subExercises: [
        {
          order: 0,
          sets: 5,
          reps: 5,
          oneRmPct: 0.7,
          exerciseName: '스쿼트',
          bodyPart: 'LEGS',
        },
        {
          order: 1,
          sets: 4,
          reps: 6,
          oneRmPct: 0.6,
          exerciseName: '데드리프트',
          bodyPart: 'LEGS',
        },
        {
          order: 2,
          sets: 3,
          reps: 8,
          oneRmPct: 0.5,
          exerciseName: '프론트 스쿼트',
          bodyPart: 'LEGS',
        },
        {
          order: 3,
          sets: 3,
          reps: 10,
          bodyPart: 'LEGS',
          oneRmPct: 0.4,
          chooseOneExercises: '레그컬, 카프레이즈 택 1개',
        },
      ],
    },
  ],
};
